---
title: Open-Source Craft
timezone: America/New_York
collections:
  episodes:
    title: Episodes
    output: true
    permalink: "/episodes/:path/"
  posts:
    title: Posts
    output: true
  uploads:
    title: Uploads
    output: true
defaults:
- scope:
    path: ''
    type: episodes
  values:
    layout: episode
    excerpt: ''
    episode_number: ''
    feature_image: ''
    audio_embed: ''
    video_embed: ''
    show_tell_embed: ''
    notes:
    - ''
email: dustin@delatore.me
description: 'The world runs on Open Source Software.  We speak to the people who
  shape our world.

'
baseurl: "/open-sourcecraft"
url:
google_analytics: UA-90157003-1
follow:
- source: facebook
  username: opensourcecraft
- source: twitter
  username: opensourcecraft
- source: instagram
  username: opensourcecraft
subscribe:
  video:
  - source: podcast
    url: podcast.com
  - source: stitcher
    url: stitcher.com
  - source: youtube
    url: youtube.com
  audio:
  - source: podcast
    url: podcast.com
  - source: stitcher
    url: stitcher.com
markdown: kramdown
sass:
  style: compressed
gems:
- jekyll-feed
- jekyll-sitemap
exclude:
- Gemfile
- Gemfile.lock
- package.json
- node_modules
