---
title: Open-Source Craft
timezone: UTC
collections:
  episodes:
    title: Episodes
    output: true
  posts:
    title: Posts
    output: true
  uploads:
    title: Uploads
    output: true
email: dustin@delatore.me
description: 'The world runs on Open Source Software.  We speak to the people who
  shape our world.

'
baseurl: ''
url: ''
markdown: kramdown
gems:
- jekyll-feed
- jekyll-sitemap
exclude:
- Gemfile
- Gemfile.lock
