---
title: Open-Source Craft
timezone: UTC
collections:
  episodes:
    title: Episodes
    output: true
    permalink: "/episodes/:path/"
  posts:
    title: Posts
    output: true
  uploads:
    title: Uploads
    output: true
defaults:
- scope:
    path: ''
    type: episodes
  values:
    layout: episode
    excerpt: ''
    episode_number: ''
    feature_image: ''
    audio_embed: ''
    video_embed: ''
    notes:
    - ''
email: dustin@delatore.me
description: 'The world runs on Open Source Software.  We speak to the people who
  shape our world.

'
baseurl: '/open-sourcecraft'
url: ''
social:
  - source: 'facebook'
    url: 'facebook.com'
  - source: 'youtube'
    url: 'youtube.com'
  - source: 'twitter'
    url: 'twitter.com'
  - source: 'instagram'
    url: 'instagram.com'
markdown: kramdown
gems:
- jekyll-feed
- jekyll-sitemap
exclude:
- Gemfile
- Gemfile.lock
- package.json
- node_modules
